#include "quads_utils.glsl"

layout(local_size_x = THREADS_PER_LOCALGROUP, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer CurrNumProxiesBuffer {
    uint currNumProxies;
};

layout(std430, binding = 1) writeonly buffer PrevNumProxiesBuffer {
    uint prevNumProxies;
};

layout(std430, binding = 2) writeonly buffer QuadCreatedFlagsBuffer {
    int quadCreatedFlags[];
};

layout(std430, binding = 3) readonly buffer NormalSphericalsBufferInput {
    uint normalSphericalsInput[];
};

layout(std430, binding = 4) readonly buffer DepthBufferInput {
    float depthsInput[];
};

layout(std430, binding = 5) readonly buffer OffsetsBufferInput {
    uint metadatasInput[];
};

layout(std430, binding = 6) writeonly buffer quadIndicesMap {
    uint quadIndices[];
};

uniform vec2 gBufferSize;

void storeQuadIndex(ivec2 pixelCoords, uint index) {
    uint pixelIndex = uint(pixelCoords.y) * uint(gBufferSize.x) + uint(pixelCoords.x);
    quadIndices[pixelIndex] = index;
}

QuadMapData loadQuadMap(uint index) {
    QuadMapDataPacked quadMapDataPacked;
    quadMapDataPacked.normalSpherical = normalSphericalsInput[index];
    quadMapDataPacked.depth = depthsInput[index];
    quadMapDataPacked.metadata = metadatasInput[index];

    QuadMapData quadMapData;
    quadMapData.normal = unpackSphericalToNormal(quadMapDataPacked.normalSpherical);
    quadMapData.depth = quadMapDataPacked.depth;

    quadMapData.offset.x = (quadMapDataPacked.metadata >> 20) & 0xFFFu;
    quadMapData.offset.y = (quadMapDataPacked.metadata >> 8) & 0xFFFu;

    uint flattenedAndSize = quadMapDataPacked.metadata & 0xFFu;
    quadMapData.size = (flattenedAndSize >> 1) & 0x7Fu;
    quadMapData.flattened = (flattenedAndSize & 1u) != 0u;

    return quadMapData;
}

void main() {
    uint quadIndex = gl_GlobalInvocationID.x;

    if (quadIndex == 0u) {
        prevNumProxies = currNumProxies;
    }

    // Reset quadCreatedFlags
    quadCreatedFlags[quadIndex] = 0;

    if (quadIndex >= currNumProxies) {
        return;
    }

    // Uncomment for debugging:
    // Ivec2 pixelCoords = ivec2(quadIndex % uint(gBufferSize.x), quadIndex / uint(gBufferSize.x));
    // StoreQuadIndex(pixelCoords, quadIndex);

    QuadMapData quadMapData = loadQuadMap(quadIndex);
    if (quadMapData.size == 0u) {
        return;
    }

    uint halfSize = 1u << (quadMapData.size - 1u); // 2^size / 2
    ivec2 proxyPlanePixelCoord = ivec2(quadMapData.offset);

    // Put quadIndex into quadIndices
    ivec2 baseCoord = proxyPlanePixelCoord;
    for (uint idx = 0u; idx < halfSize * halfSize; idx++) {
        uint i = idx % halfSize;
        uint j = idx / halfSize;
        ivec2 pixelCoords = baseCoord + ivec2(i, j);
        storeQuadIndex(pixelCoords, quadIndex);
    }
}
