#include "quads_utils.glsl"

layout(local_size_x = THREADS_PER_LOCALGROUP, local_size_y = THREADS_PER_LOCALGROUP, local_size_z = 1) in;

layout(std430, binding = 0) buffer QuadBufferSizes {
    uint numProxies;
    uint numProxiesTransparent;
    uint numDepthOffsets;
};

layout(std430, binding = 1) readonly buffer normalAndDepthBufferInput {
    uint normalAndDepthInput[];
};

layout(std430, binding = 2) readonly buffer MetadataBufferInput {
    uint metadatasInput[];
};

layout(std430, binding = 3) writeonly buffer normalAndDepthBufferOutput {
    uint normalAndDepthOutput[];
};

layout(std430, binding = 4) writeonly buffer MetadataBufferOutput {
    uint metadatasOutput[];
};

uniform vec2 gBufferSize;
uniform vec2 quadMapSize;

QuadMapData loadInputQuadMap(ivec2 pixelCoord) {
    uint index = uint(pixelCoord.y) * uint(quadMapSize.x) + uint(pixelCoord.x);

    QuadMapDataPacked quadMapDataPacked;
    quadMapDataPacked.normalAndDepth = normalAndDepthInput[index];
    quadMapDataPacked.metadata       = metadatasInput[index];

    QuadMapData quadMapData;
    quadMapData.normal = unpackOctahedralToNormal((quadMapDataPacked.normalAndDepth >> 16) & 0xFFFFu);
    quadMapData.depth  = unpackDepthUNORM16(quadMapDataPacked.normalAndDepth & 0xFFFFu);

    quadMapData.offset.x = (quadMapDataPacked.metadata >> 20) & 0xFFFu;
    quadMapData.offset.y = (quadMapDataPacked.metadata >> 8) & 0xFFFu;

    uint sizeAlphaFlattened = quadMapDataPacked.metadata & 0xFFu;
    quadMapData.size      = (sizeAlphaFlattened >> 2) & 0x7Fu;
    quadMapData.hasAlpha  = (sizeAlphaFlattened & 2u) != 0u;
    quadMapData.flattened = (sizeAlphaFlattened & 1u) != 0u;

    return quadMapData;
}

void storeOutputQuadMap(uint index, in QuadMapData quadMapData) {
    QuadMapDataPacked quadMapDataPacked;

    uint sizeAlphaFlattened = ((quadMapData.size & 0x7Fu)       << 2) |
                              ((quadMapData.hasAlpha ? 1u : 0u) << 1) |
                              (quadMapData.flattened ? 1u : 0u);
    quadMapDataPacked.metadata = ((quadMapData.offset.x & 0xFFFu) << 20) |
                                 ((quadMapData.offset.y & 0xFFFu) <<  8) |
                                 (sizeAlphaFlattened & 0xFFu);
    normalAndDepthOutput[index] = ((packNormalToOctahedral(quadMapData.normal) & 0xFFFFu) << 16) |
                                  (packDepthUNORM16(quadMapData.depth) & 0xFFFFu);
    metadatasOutput[index]      = quadMapDataPacked.metadata;
}

void main() {
    ivec2 quadMapPixelCoords = ivec2(gl_GlobalInvocationID.xy);
    if (quadMapPixelCoords.x >= int(quadMapSize.x) || quadMapPixelCoords.y >= int(quadMapSize.y)) {
        return;
    }

    QuadMapData quadMapData = loadInputQuadMap(quadMapPixelCoords);
    if (quadMapData.size == 0) {
        return;
    }

    uint size = 1 << quadMapData.size;
    bool flattened = quadMapData.flattened;
    if (!flattened) {
        // For (int i = 0; i < size; i++) {
        //     For (int j = 0; j < size; j++) {
        //         AtomicAdd(numDepthOffsets, 4);
        //     }
        // }
        atomicAdd(numDepthOffsets, size * size * 4);
    }

    uint index = atomicAdd(numProxies, 1);
    if (quadMapData.hasAlpha) {
        atomicAdd(numProxiesTransparent, 1);
    }
    storeOutputQuadMap(index, quadMapData);
}
